#!/bin/bash
# stripped & rewritten by DMD

B='\033[38;5;45m'
G='\033[38;5;46m'
Y='\033[38;5;220m'
R='\033[38;5;203m'
P='\033[38;5;135m'
N='\033[0m'
D='\033[1;90m'
UN='\033[4m' #underline
RUN='\033[24m' #reset underline

echo -e "${G}-------------------------- chromeos_startup --------------------------${N}" # lol this is so its easier to understand what happens when for me ig

get_largest_cros_blockdev() {
  local largest size dev_name tmp_size remo
  size=0
  for blockdev in /sys/block/*; do
    dev_name="${blockdev##*/}"
    echo "$dev_name" | grep -q '^\(loop\|ram\)' && continue
    tmp_size=$(cat "$blockdev"/size)
    remo=$(cat "$blockdev"/removable)
    if [ "$tmp_size" -gt "$size" ] && [ "${remo:-0}" -eq 0 ]; then
      case "$(sfdisk -l -o name "/dev/$dev_name" 2>/dev/null)" in
        *STATE*KERN-A*ROOT-A*KERN-B*ROOT-B*)
        largest="/dev/$dev_name"
        size="$tmp_size"
        ;;
      esac
    fi
  done
  echo "$largest"
}
DST=$(get_largest_cros_blockdev)
if [ -z $DST ]; then
    DST=/dev/mmcblk0
fi

# boot messages (we should add more)

# multi-liners
cat <<EOF >/usr/share/chromeos-assets/text/boot_messages/en/block_devmode_virtual.txt
ChromeOS is trying to kill itself.
ChromeOS detected developer mode and is trying to disable it to
comply with FWMP. If auto-repair fails, boot some kind of code exec and run "vpd -i RW_VPD -s block_devmode=0 && crossystem block_devmode=0"
EOF

cat <<EOF >/usr/share/chromeos-assets/text/boot_messages/en/self_repair.txt
fanxql touched your system in a way that made it feel funny
detouching system (repairing system)
EOF


cat <<EOF >/usr/share/chromeos-assets/text/boot_messages/en/enter_dev1_virtual.txt
Your system is transitioning :transgender_flag:
Local data has been cleared.
If you are seeing this message, you have already modified your system,
so google is sad :(
To cancel, turn your computer off now.
EOF

# auto repair message
cat <<EOF >/usr/share/chromeos-assets/text/boot_messages/en/anti_block_devmode_virtual.txt
ChromeOS is trying to prevent Modmium from starting
Modmium is fighting ChromeOS to get your device to boot, wish it luck.
Your system will boot in a few seconds...
EOF

# leave dev message
cat <<EOF >/usr/share/chromeos-assets/text/boot_messages/en/leave_dev.txt
You are trying to disable developer mode.
Please ensure that you have DevFW enabled, otherwise ChromeOS WILL NOT BOOT.
Your device will attempt to boot in DevFW verified in 30 seconds...
EOF

cat <<EOF >/usr/share/chromeos-assets/text/boot_messages/en/update_firmware.txt
your firmware is updating!! (if you see this message, report an issue ASAP)
https://github.com/crosmium/modmium
EOF

# single-liners
echo "your system has been FANXED! (powerwashing system)" >/usr/share/chromeos-assets/text/boot_messages/en/power_wash.txt

# chromeOS disenfuckinators
crossystem block_devmode=0
vpd -i RW_VPD -s block_devmode=0
device_management_client --action=remove_firmware_management_parameters || true
device_management_client --action=set_firmware_management_parameters --flags=0 || true

if [[ $(crossystem devsw_boot) -eq 0 ]]; then
  if [ ! -f /.policyedit_staged ]; then
    echo "Staging policyedit..."
    sed -i 's|stable-channel|testimage-channel|g' /etc/lsb-release
    echo "--disable-policy-key-verification" >>/etc/chrome_dev.conf
    echo "--disable-oobe-chromevox-hint-timer-for-testing" >>/etc/chrome_dev.conf
    echo "--disable-features=ExtensionManifestV2Unsupported" >>/etc/chrome_dev.conf
    touch /.policyedit_staged
    echo "Done"
  fi

  if [ ! -f /.sudo_enabled ]; then
    echo "Enabling sudo..."
    sed -i '1s/^/env LD_PRELOAD=\/lib\/minioverride.so\n/' /etc/init/ui.conf
    touch /.sudo_enabled
    echo "Done"
  fi

  if [ ! -f /.updates_blocked ]; then
    echo "Disabling auto-updates..."
    sed -i 's|tools.google.com|updates.google.com|g' /etc/lsb-release
    touch /.updates_blocked
    echo "Done"
  fi

  if [ -f /.deprovision ]; then
    version=$(cat /.deprovision)
    if [[ $version -lt 143 ]]; then
       vpd -i RW_VPD -s re_enrollment_key=$(openssl rand -hex 32)
    else
       sed -i '/--enterprise-enable-state-determination=never/d' /etc/chrome_dev.conf
       echo --enterprise-enable-state-determination=never >>/etc/chrome_dev.conf
    fi
  else
    vpd -i RW_VPD -d re_enrollment_key
    sed -i '/--enterprise-enable-state-determination=never/d' /etc/chrome_dev.conf
  fi
else
  crossystem disable_dev_request=1
  reboot
fi

if [ -f /root/.removeskipoobeflag ]; then
  echo "Removing one-time OOBE skip flag..."
  sed -i '/oobe-skip-to-login/d' /etc/chrome_dev.conf
  rm -f /root/.removeskipoobeflag
  echo "Done"
fi

echo -e "${G}-------------------------- Handing startup back to ChromeOS :D --------------------------${N}"
exec /sbin/chromeos_startup.old
